notifications:
  hipchat:
    rooms:
      secure: dtIZnyQ5l7HoMHAPYE/7EmZ5ic9/vJAzUjNWWPHqPjuUWuh2EYQhPaQGlN/lMrcEAg/vrDdwga/vR729TGCgE7fyiElE9oRC1A/7xwiW8bgdOzDLINkH2/QW8GfRS7J+rFN3iFxOw0jVKcynDC3dt46ZS24xaTcGz3/BDdS6E1k=
language: php
php:
- 5.4
- 5.5
- 5.6
script:
- cd $TRAVIS_BUILD_DIR
- composer install
- vendor/bin/phpunit -c ./phpunit.xml.dist --bootstrap ./tests/bootstrap.php --verbose
  --debug || exit 1
