env:
  global:
  - secure: Pub+0A1pN1RifBo091ipt0WUoatLxS0jc7ZappgoK4h2vghHdC0w90uxBiTCn4nCuSOnzeUB4oQ2qGVREMtrS4pa4p/LVkSSf1Qs207+Kj6os10B5+ecfNJ/r9kfG3+BddwJWTjYvKRy07lmGiSbfIS7GKOx3Zb8ymuul2Y3rH8=
notifications:
  hipchat:
    rooms:
      secure: dtIZnyQ5l7HoMHAPYE/7EmZ5ic9/vJAzUjNWWPHqPjuUWuh2EYQhPaQGlN/lMrcEAg/vrDdwga/vR729TGCgE7fyiElE9oRC1A/7xwiW8bgdOzDLINkH2/QW8GfRS7J+rFN3iFxOw0jVKcynDC3dt46ZS24xaTcGz3/BDdS6E1k=
language: php
php:
- 5.4
- 5.5
- 5.6
before_script:
- >
  echo "apiKey: $API_KEY" > test_configuration.local.yml
script:
- cd $TRAVIS_BUILD_DIR
- composer install
- vendor/bin/phpunit -c ./phpunit.xml.dist --bootstrap ./tests/bootstrap.php --verbose
  --debug || exit 1
